# Generated by Django 3.0.6 on 2020-06-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200604_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='cead0',
            new_name='chead0',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='cead1',
            new_name='chead1',
        ),
    ]
